import type { Metadata } from "next";
import { Quicksand as MainFont } from "next/font/google";
import "./globals.css";

const mainFont = MainFont({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dreambox",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <head></head>
      <body className={mainFont.className}>{children}</body>
    </html>
  );
}
